# Site settings
title: "Ben Grimsley - Systems Engineer"
description: "Portfolio of Ben Grimsley, Systems Engineer, specializing in space, robotics, and complex systems design."
url: "https://bengrimsley.engineer" # Your domain name
baseurl: "" # Leave empty if you are not using a subfolder

# Author info
author:
  name: "Ben Grimsley"
  email: "ben@bengrimsley.engineer" # Use your email

# Social links
social:
  github: "https://github.com/bsullgrim"
  twitter: "https://twitter.com/ben_grimsley"
  linkedin: "https://www.linkedin.com/in/ben-grimsley"
  email: "mailto:ben@bengrimsley.engineer"

# Markdown settings
markdown: kramdown

# Theme settings
theme: "minima" # You can use any theme you like

# Permalink settings (for URL structure)
permalink: "/:categories/:year/:month/:day/:title/"

# Plugins (optional, for additional functionality)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from being processed
exclude:
  - "README.md"
  - "LICENSE"
  - "Gemfile"
  - "Gemfile.lock"
  - "_config.yml"
  - "node_modules"

# Build settings
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
