title: "Ben Grimsley"  # Your name or personal brand
subtitle: "Systems Engineer | Space Enthusiast | MBSE Practitioner"  # A short tagline
description: "Welcome to my portfolio. I specialize in Model-Based Systems Engineering (MBSE), orbital platform development, and in-space manufacturing."  # Brief description for SEO
author: "Ben Grimsley"
baseurl: ""  # Leave empty if deploying to GitHub Pages at username.github.io
url: "https://bengrimsley.engineer"  # Your custom domain or GitHub Pages URL

theme: minima  # Apply the Minima theme

# Minima theme settings
minima:
  skin: auto  # Use default light/dark mode settings
  social_links:
    github: bsullgrim
    linkedin: bengrimsley
    rss: true  # Optional, removes RSS icon if set to false

# Navigation Links (optional if you want a one-page layout)
header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md

# Markdown settings
markdown: kramdown
highlighter: rouge  # Syntax highlighting for code blocks

# Plugins
plugins:
  - jekyll-seo-tag  # Improves SEO metadata
  - jekyll-feed  # Generates an RSS feed
  - jekyll-sitemap  # Creates a sitemap.xml for search engines

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
