title: "Ben Grimsley"
name: "Ben Grimsley"
description: "Systems Engineer, Space Enthusiast, and Robotics Designer."
url: "https://bengrimsley.engineer" 
baseurl: ""  # Leave empty for the root domain

# SEO
seo:
  title: "Ben Grimsley – Systems Engineer and Space Enthusiast"
  description: "Portfolio of Ben Grimsley – Systems Engineer, Space Enthusiast, and Robotics Designer."
  url: "https://bengrimsley.engineer"  
  og_title: "Ben Grimsley | Portfolio"
  og_description: "Systems Engineer, Space Enthusiast, and Robotics Designer"
  og_url: "https://bengrimsley.engineer"
